# Generated by Django 4.1.5 on 2023-09-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('megz_account_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
